apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor
  labels:
    app: flask-aws-monitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-aws-monitor
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
